### ISSUE TITLE
Having issues installing with setuptools

### ISSUE THREAD

**Issue by adi-** [jambonrose/markdown_superscript_extension#2]
```Running MarkdownSuperscript-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-L7PBlR/MarkdownSuperscript-1.0.1/egg-dist-tmp-mV3q3g

error: [Errno 2] No such file or directory: '/tmp/easy_install-L7PBlR/MarkdownSuperscript-1.0.1/DESCRIPTION.rst'```

**Comment by jambonrose** [comment]
What commands did you issue to get that output?

At a glace, it appears that only the Wheel distribution on PyPI includes the `Description.rst` file. Neither the tar nor the zip have it, which baffles me a little bit. If you can use `pip`to install the wheel version (the default if you use `pip install MarkdownSuperscript`) then you shouldn't have any problems.

I'll try to get a fix for this over the weekend.

**Comment by jambonrose** [comment]
This should now be remedied thanks to PR #4 . Please let me know if this is still an issue.
